# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'fp22-happ' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for fp22-happ
  pod 'Firebase/Firestore'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
end
